# -*- coding: utf-8 -*-
"""PYNTHON 03/07/2025

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JcgQl1e3-5mQcrsXz0CfPzOKr099elOo
"""

print('olá mundo')

"""Exercicio 1"""

x = 6 + 4 * 2
print (x)

x = (4 * 9 + 5)
print (x)

x = ((6 + 7)* 9)
print (x)

x = (15 + 20 - 30)
print (x)

x = (6 + 5 ** 2)
print (x)

numero_1 = 5
numero_1 += 5
print(numero_1)

x = 8
x += 5
x -= 4
x *= 20
x /= 2
print(x)

numero_1 = 2
numero_2 = 4
soma = numero_1 + numero_2
if soma < 10:
    print("A soma é menor que 10.")
else:
    print("A soma é 10 ou maior.")

soma1 = 7 + 8
soma2 = 10 + 5
if soma1 == soma2:
  print('Os resultados são iguais')

x = 8
x1 = 3
x_resultado = x < x1
print(x_resultado)
x_resultado = x == x1
print(x_resultado)
x_resultado = x >= x1
print(x_resultado)
x_resultado = x != x1
print(x_resultado)

idade_luacas = 21
idade_carolina = 19
if idade_luacas >=18 or idade_carolina >=18:
  print("pelo menos um dos dois é maior de idade")

idade_luacas = 21
idade_carolina = 19
if idade_luacas >=18 and idade_carolina >=18:
  print("os dois são maiores de idade")

time_carlos = 'botafogo'
time_luciano = 'flamengo'
time_fabricia = 'botafogo'
print(time_carlos is time_luciano)

x = "botafogo"
x1 = "flamengo"
x3 = "botafogo"
Xresult = x is x3
print(Xresult)  # True
Xresult = x is not x3
print(Xresult)  # False
Xresult = x1 is x3
print(Xresult)  # False
Xresult = x1 is not x3
print(Xresult)  # True

# Variáveis
X = 4
X1 = 9
X2 = 5

# 1ª expressão
XResult = (((2 + 5) * 3) + X * 5) < X1
print("1ª expressão:", XResult)  # False

# 2ª expressão
XResult = (((2 + 5) * 3) + (X <= X1)) == (X == 6 + X2 * 2)
print("2ª expressão:", XResult)  # False

# 3ª expressão
XResult = (((3 * 6) - X - 3) < X2)
print("3ª expressão:", XResult)  # False

# 4ª expressão
XResult = (((7 * 8) > (X + 4 * X1)) < (X1 - 2 + X2 * 9))
print("4ª expressão:", XResult)  # True

"""programa para saber idade"""

nota1 = float(input("Digite a primeira nota: "))
nota2 = float(input("Digite a segunda nota: "))
media = (nota1 + nota2) / 2
print(f"Média do aluno: {media:.2f}")
if media >= 7:
    print("O aluno foi aprovado.")
elif media >= 5:
    print("O aluno está de recuperação.")
else:
    print("O aluno foi reprovado.")

a = int(input("Informe um numero entre 0 e 100:"))
if a > 50:
  print("O numero",a,"é maior que 50")
elif a == 50:
  print ("O numero informado é igual a 50")
else:
  print("O numero",a,"é menor que 50")